# docker/Dockerfile.server
FROM golang:1.22-alpine

WORKDIR /app

# Copy the server code
COPY ../server ./

# Build
RUN go mod init server && go build -o server main.go

# Open port 8080
EXPOSE 8080

# Run
CMD ["./server"]
